logging:
  level:
    root: info
    org.hibernate.type.descriptor.sql: trace


spring:
  cache:
    type: redis
  data:
    #    redis:
    #      host: localhost
    #      port: 6379
    web:
      pageable:
        one-indexed-parameters: true
  #        default-page-size: 4
  messages:
    fallback-to-system-locale: false
  jpa:
    defer-datasource-initialization: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
      hibernate.use_sql_comments: true